Proj 4
Jointlab-ANZ-UESTC/TOF pull request #9
Opened 2019-04-16 09:22 UTC by big-panda

2019-04-16 09:29 UTC, WuXuan374 submitted a review, later dismissed

2019-04-17 05:10 UTC, groers requested changes
project1.py文件不能反映作用
代码缺少注释
输出输出文件推荐改名result_for_ticket4之类的形式

2019-04-17 12:18 UTC, groers reviewed
great

2019-04-17 12:18 UTC, groers approved these changes

2019-04-17 12:19 UTC, merged